settings:
  telemetry_enabled: true
active_modules:
  api:
    connections:
      evse_manager:
      - implementation_id: evse
        module_id: evse_manager
    module: API
  auth:
    module: Auth
    config_module:
      connection_timeout: 10
      selection_algorithm: PlugEvents
    connections:
      token_provider:
      - module_id: token_provider_1
        implementation_id: main
      - module_id: token_provider_rfid
        implementation_id: main
      token_validator:
      - module_id: token_validator
        implementation_id: main
      evse_manager:
      - module_id: evse_manager
        implementation_id: evse
  energy_manager:
    connections:
      energy_trunk:
      - implementation_id: energy_grid
        module_id: grid_connection_point
    module: EnergyManager
  evse_manager:
    config_module:
      ac_enforce_hlc: false
      ac_hlc_enabled: true
      ac_hlc_use_5percent: true
      ac_nominal_voltage: 230
      ac_with_soc: false
      charge_mode: AC
      country_code: DE
      dbg_hlc_auth_after_tstep: false
      ev_receipt_required: false
      evse_id: DE*PNX*E123456*1
      has_ventilation: true
      payment_enable_contract: false
      payment_enable_eim: true
      session_logging: true
      session_logging_path: /tmp/logs
      session_logging_xml: false
      three_phases: true
      connector_id: 1
    connections:
      bsp:
      - implementation_id: board_support
        module_id: yeti_driver
      hlc:
      - implementation_id: charger
        module_id: iso15118_charger
      powermeter_grid_side:
      - implementation_id: powermeter
        module_id: yeti_driver
      slac:
      - implementation_id: main
        module_id: slac
    module: EvseManager
    telemetry:
      id: 1
  grid_connection_point:
    config_module:
      fuse_limit_A: 40
      phase_count: 3
    connections:
      energy_consumer:
      - implementation_id: energy_grid
        module_id: evse_manager
    module: EnergyNode
  iso15118_charger:
    config_module:
      device: eth1
      tls_security: allow
    connections: {}
    module: EvseV2G
    connections:
      security:
        - module_id: evse_security
          implementation_id: main
  evse_security:
    module: EvseSecurity
    config_module:
      private_key_password: "123456"
  persistent_store:
    module: PersistentStore
    config_module:
      sqlite_db_file_path: /etc/everest/everest_persistent_store.db
    connections: {}
  setup:
    config_module:
      localization: true
      setup_simulation: false
      setup_wifi: true
    connections:
      store:
      - module_id: persistent_store
        implementation_id: main
    module: Setup
  slac:
    config_implementation:
      main:
        device: eth1
        evse_id: PIONIX_SAYS_HELLO
        nid: pionix!
        number_of_sounds: 10
    connections: {}
    module: EvseSlac
  token_provider_1:
    config_implementation:
      main:
        timeout: 10
        token: DEADBEEF
        type: RFID
    connections:
      evse:
      - implementation_id: evse
        module_id: evse_manager
    module: DummyTokenProvider
  token_provider_rfid:
    config_implementation:
      main:
        serial_port: /dev/ttyAMA1
    connections: {}
    module: PN532TokenProvider
  token_validator:
    config_implementation:
      main:
        sleep: 0.25
        validation_reason: Token seems valid
        validation_result: Accepted
    connections: {}
    module: DummyTokenValidator
  yeti_driver:
    telemetry:
      id: 1
    config_module:
      baud_rate: 115200
      reset_gpio: 13
      serial_port: /dev/ttyAMA0
    connections: {}
    module: YetiDriver
